### ISSUE TITLE
the deploy action still tries to create a namespace for anonymous sessions

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-actions#10]
see https://github.com/SwissDataScienceCenter/renku-python/runs/4158887459?check_suite_focus=true#step:3:2009

The extra namespace logic is no longer needed and should be removed.

**Comment by ableuler** [comment]
This has already been fixed, renku-python is using an outdated version of this action.

**Comment by ableuler** [comment]
(you might want to wait with updating though as we need to fix https://github.com/SwissDataScienceCenter/renku-actions/issues/12)
