### ISSUE TITLE
uninstall deployment after acceptance tests run

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-actions#15]
Most PR deployments are used to run acceptance tests and not really looked at by a human user. We should therefore uninstall CI deployments as soon as acceptance tests finish. We should also, however, allow devs to specify that they want a long-running deployment for e.g. testing of features by hand. Therefore the default behavior could be overriden with a flag like `--persist` to the `/deploy` command. 

Currently, _running_ the tests is the only part of the flow that is not encapsulated in a shared action. We need to create such a shared action so it can easily be used by all the repos. This action should check the `/deploy` command and in the absence of a `--persist` flag it should _delete_ the relevant release, but keep the namespace intact so we don't get into trouble with letsencrypt.

**Comment by ciyer** [comment]
This was done at some point in the last year. Closing.
